// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"1":{"path":"/","redirect":"/poker","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"桌面","path":"/poker","headerRender":false,"footerRender":false,"menuRender":false,"menuHeaderRender":false,"hideChildrenInMenu":true,"hideInMenu":true,"hideInBreadcrumb":true,"file":"@/pages/Poker/index.tsx","parentId":"ant-design-pro-layout","id":"2"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","file":"@/.umi-production/plugin-layout/Layout.tsx","isLayout":true}},
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Poker__index" */'@/pages/Poker/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'@/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
