// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export {
  proxy, useSnapshot, snapshot, subscribe,
  proxyWithComputed,
  proxyWithHistory,
  proxyWithDevtools,
  proxyMap,
  proxySet,
} from '/Users/chenchao/prj_local/prj_nodejs/poker-ui/node_modules/.pnpm/@umijs+valtio@1.0.0/node_modules/@umijs/valtio';
